name = "TK-Gaming Modpack"
author = "Ulrik Boll Djurtoft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d03bcd6d5158f6633e47b9073447b57b17de4beb5e7bf2b5daee6570edaf301e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.182"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "config/openloader/data"
