name = "TK-Gaming Modpack"
author = "Ulrik Boll Djurtoft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a599b62171e2e7b92d3901d3749f5f6e8c04c7e8a774af3997cdbaf66f58e2d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.182"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "config/openloader/data"
