name = "TK-Gaming Modpack"
author = "Ulrik Boll Djurtoft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee7a9bb504d0e77855612c72b08d1d02dcd606ffe1354b68b6b8e779552b58aa"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
