name = "TK-Gaming Modpack"
author = "Ulrik Boll Djurtoft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8eeb279fd58c99cb97e047991830652dc6310cc3f1a942b531f7a1ca5cfc772"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.208"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "config/openloader/data"
